# Generated by Django 5.2.6 on 2025-09-14 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('date_scraped', models.DateTimeField(auto_now_add=True)),
                ('vector_db_id', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ScrapedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('headings', models.TextField(blank=True)),
                ('paragraphs', models.TextField(blank=True)),
                ('list_items', models.TextField(blank=True)),
                ('combined_text', models.TextField(blank=True)),
                ('word_count', models.IntegerField(default=0)),
                ('url_hash', models.CharField(blank=True, max_length=100)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='api.website')),
            ],
        ),
    ]
